theme: minima
title: Shinzie Tandun
description: portofolio
minima:
  social_links:
    - platform: deviantart  # same as SVG filename.
      user_url: "https://www.deviantart.com/john.doe"  # URL of profile page.
      title:  My profile at DeviantArt.com  # Optional. Text displayed on hovering over link.