theme: minima
title: GitHub Portofolio
description: |
  😄 My Pronouns: She/Her  
  🔭 I'm currently working on...  
  🌱 I'm currently learning ...  
author: Shinzie Tandun
email: "shinzietandun@gmail.com"

# Social links
github_username:  s-tandun
gitlab_username: s-tandun
linkedin_username: shinzietandun
rss: rss
