theme: minima
title: Shinzie Tandun
description: "😄 My Pronouns: She/Her \n 🔭 I’m currently working on... \n 🌱 I’m currently learning ..." 
author: Shinzie Tandun
email: "shinzietandun@gmail.com"

header_pages:
  - /#skills
  - /#education
  - /#project

# Social links
github_username:  s-tandun
gitlab_username: s-tandun
linkedin_username: shinzietandun
rss: rss
