theme: minima
title: Shinzie Tandun
description: |
  😄 My Pronouns: She/Her<br>
  🔭 I'm currently working on...<br>
  🌱 I'm currently learning ...
author: Shinzie Tandun
email: "shinzietandun@gmail.com"

# Social links
github_username:  s-tandun
gitlab_username: s-tandun
linkedin_username: shinzietandun
rss: rss
