theme: minima
title: Shinzie Tandun
description: portofolio
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }